### ISSUE TITLE
Join the bot to a Server ?

### ISSUE THREAD

**Issue by jzuellig** [ljgago/MusicBot#2]
how do i join the bot to a discord server ?

**Comment by ljgago** [comment]
Hi, first you need create a bot like here https://goo.gl/s13SMd, and replace YOUR_CLIENT_ID_HERE in this URL:
https://discordapp.com/oauth2/authorize?&client_id=YOUR_CLIENT_ID_HERE&scope=bot&permissions=0

**Comment by iGlaedr** [comment]
Now i can not eaven build your Container any more.

It hangs at:
 `Executing busybox-1.27.2-r7.trigger
OK: 72 MiB in 62 packages
WARNING: ca-certificates.crt does not contain exactly one certificate or CRL: skipping
 ---> b50a43c999c0
Removing intermediate container 1b3aa6fdd315
Step 4/7 : RUN CGO_ENABLED=0 go get github.com/ljgago/MusicBot
 ---> Running in 3305c3660a1a`
Docker host is vmware photoos

**Comment by jzuellig** [comment]
It worked thanks for the help, but while i'm here:
How do I join the bot to an other Discord Server ?
Which isn't under my control.

**Comment by ljgago** [comment]
You need open this link again: https://discordapp.com/oauth2/authorize?&client_id=YOUR_CLIENT_ID_HERE&scope=bot&permissions=0
and select your server.
If you share this link, anyone can add the bot in own server, you can't get control of this.

**Comment by jzuellig** [comment]
Thanks for the Fast Help

**Comment by jzuellig** [comment]
Hi it's me again

The bot is on the server and accepts commands.
But it can't play YouTube nor Soundcloud links and returns: 
`[Music] I can't found this song!`

My command was 
`$play https://soundcloud.com/weareriot/themob`
and 
`$play https://www.youtube.com/watch?v=b_cHOXYkC3U`
Am i just to stupid to use your bot?

**Comment by ljgago** [comment]
Hi, the bot use the youtube API for query search and result return, so you need to generate a youtube token to use its API.
https://developers.google.com/youtube/v3/getting-started?hl=en-419
(the bot does't support soundcloud)
